# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b913bb3f34b4189644696d7c6ca5aaaaafdaae6715982d2bb93c7016e4dcec3ac46b9f1177cb9775cb19eed274c3505f86b880fa3e649800b358d45b645c0d8

test:
  secret_key_base: 28347fb62d10349294b4bed698af30eb335f65b38b25df8e76aed4fe0491877cdc14c6c95486eaebea01b828145b34a141e3e61fcd94d78eaeb2f9acb568cb3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
